package com.exam.validator;

public enum AnswerTypes {
    CORRECT_ANSWER_COUNT,
    INCORRECT_OR_PARTIAL_ANSWER_COUNT,
    CORRECT_OPTION_COUNT,
    INCORRECT_OPTION_COUNT,
    CORRECT_NOT_CHOSEN_OPTION_COUNT,
    EQUAL_NEIGHBOURS_DOMINANT_ANSWER_COUNT,
    EQUAL_NEIGHBOURS_DOMINANT_INCORRECT_ANSWER_COUNT,
    EQUAL_NEIGHBOURS_DOMINANT_OPTION_COUNT,
    NEIGHBOURS_CORRECT_NOT_CHOSEN_OPTION_COUNT,
    NEIGHBOURS_INCORRECT_NOT_CHOSEN_OPTION_COUNT,
}
